"""
Streamlit UI for Content Creator Agent
"""
import streamlit as st
import json
import os
from pathlib import Path
from content_agent import ContentCreatorAgent
from content_context import ContextManager

# Page config
st.set_page_config(
    page_title="Content Creator Agent",
    page_icon="📚",
    layout="wide"
)

# Initialize session state
if "content_agent" not in st.session_state:
    try:
        st.session_state.content_agent = ContentCreatorAgent()
    except Exception as e:
        st.error(f"Failed to initialize agent: {str(e)}")
        st.stop()

if "roadmap_json" not in st.session_state:
    st.session_state.roadmap_json = None

if "generated_content" not in st.session_state:
    st.session_state.generated_content = None

if "generated_quiz" not in st.session_state:
    st.session_state.generated_quiz = None

if "current_subtopic" not in st.session_state:
    st.session_state.current_subtopic = None


def display_action(action):
    """Display an action with appropriate icon and styling"""
    action_type = action.get("type", "info")
    message = action.get("message", "")
    
    if action_type == "success":
        st.success(f"✅ {message}")
    elif action_type == "error":
        st.error(f"❌ {message}")
    elif action_type == "warning":
        st.warning(f"⚠️ {message}")
    else:
        st.info(f"ℹ️ {message}")


def render_latex_in_markdown(content: str):
    """Render markdown content with LaTeX support"""
    # Streamlit supports LaTeX natively in markdown
    # For very long content, render in chunks to avoid performance issues
    if len(content) > 100000:  # Very long content (>100k chars)
        # Split into logical chunks (by sections)
        sections = content.split('\n## ')
        if len(sections) > 1:
            # Render first section
            st.markdown('## ' + sections[0] if not sections[0].startswith('#') else sections[0])
            # Render remaining sections
            for section in sections[1:]:
                st.markdown('---')
                st.markdown('## ' + section)
        else:
            # Fallback: split by size
            chunk_size = 50000
            chunks = [content[i:i+chunk_size] for i in range(0, len(content), chunk_size)]
            for i, chunk in enumerate(chunks):
                st.markdown(chunk)
                if i < len(chunks) - 1:
                    st.markdown("---")
    else:
        # Render normally for content < 100k chars
        st.markdown(content)


def display_quiz(quiz_data):
    """Display quiz questions"""
    if not quiz_data or not isinstance(quiz_data, list):
        st.warning("No quiz questions available")
        return
    
    st.markdown("## 📝 Quiz Questions")
    
    for i, question in enumerate(quiz_data, 1):
        with st.expander(f"Question {i} ({question.get('difficulty', 'unknown').upper()})"):
            st.markdown(f"**{question.get('question', '')}**")
            
            q_type = question.get("type", "")
            
            if q_type == "multiple_choice":
                options = question.get("options", [])
                st.markdown("**Options:**")
                for j, option in enumerate(options, 1):
                    st.markdown(f"{j}. {option}")
            
            st.markdown("---")
            st.markdown(f"**Correct Answer:** {question.get('correct_answer', '')}")
            st.markdown(f"**Explanation:** {question.get('explanation', '')}")


# Main UI
st.title("📚 Content Creator Agent")
st.markdown("Generate comprehensive educational content stepwise for each subtopic in your roadmap")

# Sidebar
with st.sidebar:
    st.header("📁 Upload Roadmap")
    st.markdown("Upload the roadmap JSON file generated by the Roadmap Generator Agent")
    
    uploaded_file = st.file_uploader(
        "Choose roadmap JSON file",
        type=["json"],
        help="Upload the roadmap JSON file"
    )
    
    if uploaded_file:
        try:
            roadmap_json = json.load(uploaded_file)
            st.session_state.roadmap_json = roadmap_json
            st.success("Roadmap loaded successfully!")
            
            # Display roadmap info
            teaching_style = roadmap_json.get("TeachingStyle", "normal")
            st.info(f"**Teaching Style:** {teaching_style}")
            
            # Show subtopics
            subtopics = {k: v for k, v in roadmap_json.items() if k.startswith("Subtopic")}
            st.markdown(f"**Total Subtopics:** {len(subtopics)}")
            
        except json.JSONDecodeError:
            st.error("Invalid JSON file. Please upload a valid roadmap JSON.")
        except Exception as e:
            st.error(f"Error loading roadmap: {str(e)}")
    
    st.markdown("---")
    
    # Context viewer
    st.header("📊 Progress")
    context_manager = st.session_state.content_agent.context_manager
    completed_ids = context_manager.get_completed_subtopic_ids()
    
    if completed_ids:
        st.success(f"**Completed:** {len(completed_ids)} subtopic(s)")
        for subtopic_id in completed_ids:
            st.markdown(f"- {subtopic_id}")
    else:
        st.info("No subtopics completed yet")
    
    # Reset context button
    if st.button("🔄 Reset Context", help="Clear all completed subtopics"):
        context_manager.reset_context()
        st.session_state.generated_content = None
        st.session_state.generated_quiz = None
        st.rerun()

# Main content area
if st.session_state.roadmap_json:
    roadmap_json = st.session_state.roadmap_json
    
    # Get current subtopic info
    context_manager = st.session_state.content_agent.context_manager
    completed_ids = context_manager.get_completed_subtopic_ids()
    all_subtopics = sorted(
        [k for k in roadmap_json.keys() if k.startswith("Subtopic")],
        key=lambda x: int(x.replace("Subtopic", ""))
    )
    
    next_subtopic_id = None
    for subtopic_id in all_subtopics:
        if subtopic_id not in completed_ids:
            next_subtopic_id = subtopic_id
            break
    
    if not next_subtopic_id:
        st.success("🎉 All subtopics have been completed!")
        
        # Generate mega quiz button
        if st.button("📝 Generate Mega Quiz"):
            with st.spinner("Generating comprehensive quiz covering all subtopics..."):
                mega_quiz = st.session_state.content_agent.generate_mega_quiz()
                
                if "error" not in mega_quiz:
                    st.session_state.mega_quiz = mega_quiz
                    st.success("Mega quiz generated successfully!")
                    st.rerun()
                else:
                    st.error(mega_quiz.get("error", "Failed to generate mega quiz"))
        
        # Display mega quiz if available
        if "mega_quiz" in st.session_state:
            st.markdown("---")
            display_quiz(st.session_state.mega_quiz.get("questions", []))
    else:
        next_subtopic_data = roadmap_json.get(next_subtopic_id, {})
        topic_name = next_subtopic_data.get("TopicName", "")
        time_to_complete = next_subtopic_data.get("SuggestedTimeToComplete", "")
        
        st.markdown("---")
        st.markdown(f"### Current Subtopic: {next_subtopic_id}")
        st.markdown(f"**Topic:** {topic_name}")
        st.markdown(f"**Estimated Time:** {time_to_complete}")
        
        # Generate content button
        if st.button(f"🚀 Generate Content for {next_subtopic_id}", type="primary"):
            # Create progress container
            progress_container = st.container()
            status_container = st.container()
            
            with progress_container:
                progress_bar = st.progress(0)
                status_text = st.empty()
            
            try:
                # Initialize state
                initial_state = {
                    "roadmap_json": roadmap_json,
                    "messages": [],
                    "actions": [],
                    "content_complete": False
                }
                
                # Track progress through nodes
                node_progress = {
                    "load_roadmap": 10,
                    "load_context": 20,
                    "research_content": 40,
                    "generate_content": 60,
                    "generate_graphs": 75,
                    "generate_quiz": 85,
                    "save_context": 100
                }
                
                # Run the graph
                result = None
                with status_container:
                    status_text.info("🔄 Starting content generation...")
                    progress_bar.progress(5)
                    
                    # Invoke graph
                    result = st.session_state.content_agent.graph.invoke(initial_state)
                    
                    progress_bar.progress(100)
                    status_text.success("✅ Content generation complete!")
                
                # Display actions
                actions = result.get("actions", [])
                if actions:
                    with status_container:
                        st.markdown("### 🔄 Generation Process")
                        for action in actions:
                            display_action(action)
                    
                    # Show final stats
                    content_length = len(result.get("generated_content", ""))
                    if content_length > 0:
                        st.success(f"✅ Generated {content_length:,} characters of content")
                
                # Store results
                st.session_state.generated_content = result.get("generated_content")
                st.session_state.generated_quiz = result.get("generated_quiz")
                st.session_state.current_subtopic = next_subtopic_id
                st.session_state.generated_graphs = result.get("generated_graphs", [])
                
                st.rerun()
                
            except Exception as e:
                with status_container:
                    st.error(f"❌ Error generating content: {str(e)}")
                    import traceback
                    with st.expander("🔍 Error Details"):
                        st.code(traceback.format_exc())
        
        # Display generated content
        if st.session_state.generated_content and st.session_state.current_subtopic == next_subtopic_id:
            st.markdown("---")
            st.markdown("## 📖 Generated Content")
            
            # Show content stats
            content = st.session_state.generated_content
            content_length = len(content)
            word_count = len(content.split())
            reading_time = max(1, word_count // 200)  # Average reading speed: 200 words/min
            
            col1, col2, col3 = st.columns(3)
            with col1:
                st.metric("Characters", f"{content_length:,}")
            with col2:
                st.metric("Words", f"{word_count:,}")
            with col3:
                st.metric("Reading Time", f"~{reading_time} min")
            
            # Count content elements
            equations = content.count("$$") // 2 + content.count("$") // 2
            examples = content.lower().count("example")
            sections = content.count("##")
            
            st.info(f"📊 Content includes: {equations} equations, {examples} examples, {sections} sections")
            
            # Display full content in a scrollable container
            st.markdown("### 📄 Full Content")
            st.markdown(
                '<div style="max-height: 900px; overflow-y: auto; border: 2px solid #4CAF50; padding: 20px; border-radius: 10px; background-color: #f9f9f9;">',
                unsafe_allow_html=True
            )
            render_latex_in_markdown(content)
            st.markdown('</div>', unsafe_allow_html=True)
            
            # Also provide expandable view
            with st.expander("📋 View Content Summary", expanded=False):
                # Show first 1000 chars as preview
                preview = content[:1000] + "..." if len(content) > 1000 else content
                st.markdown(preview)
            
            # Display graphs if any
            if st.session_state.get("generated_graphs"):
                st.markdown("---")
                st.markdown("## 📊 Generated Graphs")
                for i, graph in enumerate(st.session_state.generated_graphs, 1):
                    with st.expander(f"Graph {i}: {graph.get('title', 'Untitled')}"):
                        st.markdown(f"**Type:** {graph.get('type', 'unknown')}")
                        st.markdown(f"**Description:** {graph.get('description', '')}")
                        st.code(graph.get('code', ''), language='python')
            
            # Display quiz
            if st.session_state.generated_quiz:
                st.markdown("---")
                display_quiz(st.session_state.generated_quiz)
            
            # Download buttons
            st.markdown("---")
            col1, col2 = st.columns(2)
            
            with col1:
                if st.button("📥 Download Content"):
                    content_file = f"{next_subtopic_id}_content.md"
                    st.download_button(
                        label="Download Markdown",
                        data=st.session_state.generated_content,
                        file_name=content_file,
                        mime="text/markdown"
                    )
            
            with col2:
                if st.session_state.generated_quiz:
                    quiz_json = json.dumps({
                        "subtopic_id": next_subtopic_id,
                        "questions": st.session_state.generated_quiz
                    }, indent=2)
                    st.download_button(
                        label="📥 Download Quiz",
                        data=quiz_json,
                        file_name=f"{next_subtopic_id}_quiz.json",
                        mime="application/json"
                    )
    
    # Show all completed subtopics
    if completed_ids:
        st.markdown("---")
        st.markdown("## ✅ Completed Subtopics")
        
        for subtopic_id in completed_ids:
            with st.expander(f"{subtopic_id} - View Full Content", expanded=False):
                # Try to load content from file
                content_file = f"generated_content/{subtopic_id}/content.md"
                if os.path.exists(content_file):
                    with open(content_file, 'r', encoding='utf-8') as f:
                        content = f.read()
                    
                    # Show stats
                    content_length = len(content)
                    st.info(f"📊 Content length: {content_length:,} characters")
                    
                    # Display full content in scrollable container
                    st.markdown(
                        '<div style="max-height: 600px; overflow-y: auto; border: 1px solid #ddd; padding: 15px; border-radius: 5px;">',
                        unsafe_allow_html=True
                    )
                    render_latex_in_markdown(content)
                    st.markdown('</div>', unsafe_allow_html=True)
                else:
                    st.info("Content file not found")

else:
    st.info("👈 Please upload a roadmap JSON file to get started")
    
    # Show sample structure
    with st.expander("📋 Expected Roadmap Structure"):
        st.json({
            "TeachingStyle": "normal",
            "Subtopic1": {
                "TopicName": "Example Topic",
                "ContentList": {
                    "topics": ["Topic 1", "Topic 2"],
                    "videos": [],
                    "blogs": [],
                    "books": []
                },
                "SuggestedTimeToComplete": "2-3 weeks"
            }
        })

# Footer
st.markdown("---")
st.markdown("""
### 🔧 Environment Variables Required:
- `GOOGLE_API_KEY`: For Gemini-powered content generation
""")

