/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.29.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type { FunctionReference } from "convex/server";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export const api: {
  chat: {
    create: FunctionReference<
      "mutation",
      "public",
      {
        contextChunks: Array<{
          text: string;
          type: string;
          subtopicName?: string;
        }>;
        message: string;
        response: string;
        userId: string;
        workspaceId: string;
      },
      any
    >;
    list: FunctionReference<
      "query",
      "public",
      { workspaceId: string },
      any
    >;
  };
  content: {
    create: FunctionReference<
      "mutation",
      "public",
      {
        content: string;
        contentHtml?: string;
        errorMessage?: string;
        graphs: Array<any>;
        quiz: Array<any>;
        roadmapId: string;
        status: "pending" | "generating" | "completed" | "error";
        subtopicId: string;
        subtopicName: string;
        workspaceId: string;
      },
      any
    >;
    get: FunctionReference<"query", "public", { contentId: string }, any>;
    getByRoadmapSubtopic: FunctionReference<
      "query",
      "public",
      { roadmapId: string; subtopicId: string },
      any
    >;
    listByRoadmap: FunctionReference<
      "query",
      "public",
      { roadmapId: string },
      any
    >;
    listByWorkspace: FunctionReference<
      "query",
      "public",
      { workspaceId: string },
      any
    >;
    remove: FunctionReference<
      "mutation",
      "public",
      { contentId: string },
      any
    >;
    update: FunctionReference<
      "mutation",
      "public",
      {
        content?: string;
        contentHtml?: string;
        contentId: string;
        errorMessage?: string;
        graphs?: Array<any>;
        quiz?: Array<any>;
        status?: "pending" | "generating" | "completed" | "error";
      },
      any
    >;
  };
  embeddings: {
    create: FunctionReference<
      "mutation",
      "public",
      {
        contentId?: string;
        embedding: Array<number>;
        metadata: {
          subtopicId?: string;
          subtopicName?: string;
          title?: string;
          type: "roadmap" | "content" | "quiz" | "graph";
        };
        roadmapId?: string;
        text: string;
        workspaceId: string;
      },
      any
    >;
    search: FunctionReference<
      "query",
      "public",
      { embedding: Array<number>; workspaceId: string; limit?: number },
      any
    >;
  };
  roadmaps: {
    create: FunctionReference<
      "mutation",
      "public",
      {
        createdBy: string;
        description?: string;
        roadmapJson: any;
        sessionId?: string;
        status: "draft" | "generating" | "completed" | "error";
        teachingStyle: string;
        title: string;
        uploadedFileId?: string;
        workspaceId: string;
      },
      any
    >;
    get: FunctionReference<"query", "public", { roadmapId: string }, any>;
    list: FunctionReference<
      "query",
      "public",
      { workspaceId: string },
      any
    >;
    listByWorkspace: FunctionReference<
      "query",
      "public",
      { workspaceId: string },
      any
    >;
    remove: FunctionReference<
      "mutation",
      "public",
      { roadmapId: string },
      any
    >;
    update: FunctionReference<
      "mutation",
      "public",
      {
        description?: string;
        roadmapId: string;
        roadmapJson?: any;
        status?: "draft" | "generating" | "completed" | "error";
        title?: string;
      },
      any
    >;
  };
  workspaces: {
    addMember: FunctionReference<
      "mutation",
      "public",
      {
        role: "member" | "viewer";
        userId: string;
        workspaceId: string;
      },
      any
    >;
    create: FunctionReference<
      "mutation",
      "public",
      { description?: string; name: string; ownerId: string },
      any
    >;
    get: FunctionReference<"query", "public", { workspaceId: string }, any>;
    list: FunctionReference<"query", "public", { userId: string }, any>;
    remove: FunctionReference<
      "mutation",
      "public",
      { workspaceId: string },
      any
    >;
    update: FunctionReference<
      "mutation",
      "public",
      { description?: string; name?: string; workspaceId: string },
      any
    >;
  };
};

export const internal: typeof api;
