/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.29.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import { makeFunctionReference } from "convex/server";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export const api = {
  chat: {
    create: makeFunctionReference("chat:create"),
    list: makeFunctionReference("chat:list"),
  },
  content: {
    create: makeFunctionReference("content:create"),
    get: makeFunctionReference("content:get"),
    getByRoadmapSubtopic: makeFunctionReference("content:getByRoadmapSubtopic"),
    listByRoadmap: makeFunctionReference("content:listByRoadmap"),
    listByWorkspace: makeFunctionReference("content:listByWorkspace"),
    remove: makeFunctionReference("content:remove"),
    update: makeFunctionReference("content:update"),
  },
  embeddings: {
    create: makeFunctionReference("embeddings:create"),
    search: makeFunctionReference("embeddings:search"),
  },
  roadmaps: {
    create: makeFunctionReference("roadmaps:create"),
    get: makeFunctionReference("roadmaps:get"),
    list: makeFunctionReference("roadmaps:listByWorkspace"),
    listByWorkspace: makeFunctionReference("roadmaps:listByWorkspace"),
    remove: makeFunctionReference("roadmaps:remove"),
    update: makeFunctionReference("roadmaps:update"),
  },
  workspaces: {
    addMember: makeFunctionReference("workspaces:addMember"),
    create: makeFunctionReference("workspaces:create"),
    get: makeFunctionReference("workspaces:get"),
    list: makeFunctionReference("workspaces:list"),
    remove: makeFunctionReference("workspaces:remove"),
    update: makeFunctionReference("workspaces:update"),
  },
};

export const internal = api;
