/* eslint-disable */
/**
 * Generated data model types.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.29.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type { AnyDataModel, GenericId } from "convex/server";

/**
 * No `schema.ts` file found!
 *
 * This generated code has permissive types.
 *
 * Consider adding a `schema.ts` file to your Convex directory:
 * https://docs.convex.dev/using/schemas
 */
export type DataModel = AnyDataModel;

/**
 * Type representing a Convex document ID for a specific table.
 */
export type Id<TableName extends string = string> = GenericId<TableName>;
